add build_ros.sh, fix Undefined reference to symbol '_ZN5boost6system15system_categoryEv' https://github.com/raulmur/ORB_SLAM2/issues/494#issuecomment-354346674
Changes to be committed:
	modified:   Examples/ROS/ORB_SLAM2/CMakeLists.txt
	new file:   build_ros.sh